#!/usr/bin/env python3
"""Generate docker-compose.portable.yml — a single, self-contained stack file.

Every bind-mounted config folder/file in docker-compose.yml is inlined as a
top-level `configs:` entry with `content:`, so the output can be pasted anywhere
(Portainer / Dockge / a bare host) with NO sibling folders. Named data volumes
are kept as-is.

Secrets are never written into the file:
  * pve-exporter auth is a synthetic config built from ${PVE_*} env vars.
  * the narrator reads NTFY_*, ARGUS_*, OPENROUTER_* etc. from the environment.

`$` in real config files (Prometheus uses {{ $labels }} / {{ $value }}) is
escaped to `$$` so Compose interpolation leaves it intact; the container sees the
original `$`. The synthetic pve config intentionally keeps live `${PVE_*}`.

Single source of truth: re-run after editing any config —  `make portable`.
"""
from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
NARRATOR_IMAGE_TAG = "${ARGUS_TAG:-latest}"

# narrator runtime settings — fed from the environment (Portainer UI / .env / -e),
# with the same defaults the narrator itself uses. PROMETHEUS_URL is the in-network
# service name and is fixed.
NARRATOR_ENV = {
    "ARGUS_SITE": "${ARGUS_SITE:-homelab}",
    "ARGUS_EXTERNAL_URL": "${ARGUS_EXTERNAL_URL:-http://localhost:8088}",
    "PROMETHEUS_URL": "http://prometheus:9090",
    "NTFY_SERVER": "${NTFY_SERVER:-https://ntfy.sh}",
    "NTFY_TOPIC": "${NTFY_TOPIC:-argus}",
    "NTFY_TOKEN": "${NTFY_TOKEN:-}",
    "PEER_NARRATOR_URL": "${PEER_NARRATOR_URL:-}",
    "PEER_SITE": "${PEER_SITE:-}",
    "WATCHDOG_DEADLINE_SECONDS": "${WATCHDOG_DEADLINE_SECONDS:-180}",
    "NARRATOR_LOG_LEVEL": "${NARRATOR_LOG_LEVEL:-INFO}",
    "OPENROUTER_API_KEY": "${OPENROUTER_API_KEY:-}",
    "OPENROUTER_MODEL": "${OPENROUTER_MODEL:-anthropic/claude-3.5-sonnet}",
    "OPENROUTER_BASE_URL": "${OPENROUTER_BASE_URL:-https://openrouter.ai/api/v1}",
    "LLM_ENABLED": "${LLM_ENABLED:-true}",
}

# pve-exporter reads /etc/pve.yml; the token comes from the environment at deploy
# time, so it is never persisted in the portable file.
# token_value is optional so the stack runs even without Proxmox; set
# PVE_TOKEN_VALUE to enable pve-exporter auth.
PVE_SYNTHETIC = """\
default:
  user: ${PVE_USER:-argus@pve}
  token_name: ${PVE_TOKEN_NAME:-monitoring}
  token_value: ${PVE_TOKEN_VALUE:-}
  verify_ssl: false
"""

HEADER = """\
# ============================================================================
# Argus — SELF-CONTAINED stack. Generated by scripts/gen-portable-compose.py.
# DO NOT EDIT BY HAND — edit the source configs and run `make portable`.
#
# Paste-anywhere deploy (Portainer/Dockge/bare host): this single file carries
# every config inline; no sibling folders required.
#
#   1. Provide environment variables (Portainer env UI, an .env file, or -e):
#        ARGUS_SITE, ARGUS_EXTERNAL_URL, NTFY_SERVER, NTFY_TOPIC, NTFY_TOKEN,
#        PEER_NARRATOR_URL, PEER_SITE, and (for Proxmox) PVE_TOKEN_VALUE.
#   2. docker compose -f docker-compose.portable.yml up -d
# ============================================================================
"""


def esc(text: str) -> str:
    """Escape `$` so Compose interpolation leaves real config content intact."""
    return text.replace("$", "$$")


class _Literal(str):
    pass


def _literal_representer(dumper, data):
    return dumper.represent_scalar("tag:yaml.org,2002:str", str(data), style="|")


yaml.add_representer(_Literal, _literal_representer)


def main() -> int:
    compose = yaml.safe_load((ROOT / "docker-compose.yml").read_text())
    configs: dict[str, str] = {}

    def slug(rel: str) -> str:
        return rel.replace("/", "_").replace(".", "_").replace("-", "_")

    for name, svc in compose["services"].items():
        kept_volumes: list[str] = []
        svc_configs: list[dict] = list(svc.get("configs", []))

        for vol in svc.get("volumes", []):
            src, dst, *rest = vol.split(":")
            if not src.startswith("./"):
                kept_volumes.append(vol)  # named data volume — keep
                continue
            path = ROOT / src[2:]
            if path.is_dir():
                for f in sorted(p for p in path.rglob("*") if p.is_file()):
                    rel = f.relative_to(ROOT)
                    key = slug(str(rel))
                    configs[key] = esc(f.read_text())
                    svc_configs.append({"source": key, "target": f"{dst}/{f.relative_to(path)}"})
            elif path.is_file():
                key = slug(src[2:])
                configs[key] = esc(path.read_text())
                svc_configs.append({"source": key, "target": dst})
            # missing source (e.g. gitignored secret pve.yml) -> dropped; handled below

        if kept_volumes:
            svc["volumes"] = kept_volumes
        else:
            svc.pop("volumes", None)
        if svc_configs:
            svc["configs"] = svc_configs

    # narrator: env from environment, image pinned via ARGUS_TAG
    narr = compose["services"]["narrator"]
    narr.pop("env_file", None)
    narr["image"] = f"ghcr.io/xniicki/argus-narrator:{NARRATOR_IMAGE_TAG}"
    narr["environment"] = dict(NARRATOR_ENV)

    # pve-exporter: synthetic, env-driven auth (NOT escaped — we want interpolation)
    pve = compose["services"].get("pve-exporter")
    if pve is not None:
        configs["pve_yml"] = PVE_SYNTHETIC
        pve.setdefault("configs", []).append({"source": "pve_yml", "target": "/etc/pve.yml"})

    compose["configs"] = {k: {"content": _Literal(v)} for k, v in configs.items()}

    out = ROOT / "docker-compose.portable.yml"
    body = yaml.dump(compose, sort_keys=False, default_flow_style=False, width=4096)
    out.write_text(HEADER + body)
    print(f"wrote {out.relative_to(ROOT)}  ({len(configs)} inlined configs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
